version: "2.1"

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextcloud-23
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/INPUT_YOUR_TZ
      - REDIS_HOST=redis-nextcloud
      - REDIS_HOST_PASSWORD=your_redis_password
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini
    ports:
      - 8083:80
    restart: unless-stopped
    depends_on:
      - postgres-nextcloud
      - redis-nextcloud
    networks:
      - default

  postgres-nextcloud:
    image: postgres:14.1-alpine
    container_name: postgres-nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=your_pgsql_password
    volumes:
      - ./DB:/var/lib/postgresql/data
    networks:
      - default

  redis-nextcloud:
    image: redis:alpine
    container_name: redis-nextcloud
    command: redis-server --requirepass your_redis_password
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: docnet
